image: debian:10-slim

# Build with GCC / G++.
build_gcc:
  stage: build
  before_script:
    - apt-get update && apt-get -y --no-install-recommends install catch cmake g++ git libdevil-dev make pkg-config
    - export CC=gcc && export CXX=g++
  script:
    - mkdir ./build
    - cd ./build
    - cmake ../
    - make -j4
    - ctest -V

# Build with Clang / Clang++.
build_clang:
  stage: build
  before_script:
    - apt-get update && apt-get -y --no-install-recommends install catch clang cmake git libdevil-dev make pkg-config
    - export CC=clang && export CXX=clang++
  script:
    - mkdir ./build
    - cd ./build
    - cmake ../
    - make -j4
    - ctest -V

# Debian package creation
package_debian10:
  image: debian:10
  stage: build
  before_script:
    - ./ci/gitlab-01-install-dependencies.sh
  script:
    - ./ci/gitlab-02-create-package.sh
  only:
    - tags
  artifacts:
    paths:
      - "dds2png*.deb"
