language: cpp
compiler:
  - clang
  - gcc
sudo: false
dist: focal
os:
  - linux
arch:
  - arm64
before_install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-9" CC="gcc-9"; fi
script:
  - mkdir ./build
  - cd ./build
  - cmake ..
  - make -j4
  - ctest -V
addons:
  apt:
    packages:
    - catch
    - cmake
    - git
    - g++-9
    - libdevil-dev
notifications:
  email: false
