name: GCC

on: push

jobs:
  build_ubuntu_gcc:
    strategy:
      matrix:
        version: [8, 9, 10]
    runs-on: ubuntu-20.04
    steps:
      # Checks-out the repository under $GITHUB_WORKSPACE.
      - uses: actions/checkout@v3
      - name: Install Debian packages
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends catch cmake g++-${{ matrix.version }} git libdevil-dev make pkg-config
      - name: Build with GNU GCC ${{ matrix.version }}
        run: |
          export CXX=g++-${{ matrix.version }}
          export CC=gcc-${{ matrix.version }}
          cd $GITHUB_WORKSPACE
          mkdir build
          cd build
          cmake ../
          make -j4
      - name: Tests
        run: |
          cd "$GITHUB_WORKSPACE"/build
          ctest -V
